services:

  app:
    build:
      context: ./app
    container_name: ai-catalog-erichment
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./app/src:/app
      - ./uploads:/app/uploads
    environment:
      WATCHFILES_FORCE_POLLING: "true"
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      qdrant:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: local-postgres
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U myuser"
        ]
      interval: 5s
      retries: 5

  redis:

    image: redis:7-alpine
    container_name: local-redis
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: local-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: